apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: cicd
  labels:
    service: customer
spec:
  selector:
    service: customer
  ports:
    - port: 9002
      targetPort: 9002
  type: ClusterIP
